services:
  db:
    image: mysql
    restart: always
    container_name: be-template-db
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=template-be
    expose:
      - 3306
    ports:
      - 3333:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - be-template-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-template-be
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./views:/app/views
      - ./public:/app/public
    depends_on:
      - db
      - rabbitmq
      - otel-collector
    networks:
      - be-template-network

  rabbitmq:
    container_name: be-template-queue
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - be-template-network

  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: be-template-jaeger
    ports:
      - '16686:16686' # Jaeger UI
      - '14268:14268' # Jaeger gRPC endpoint (optional, not required for HTTP)
      - '14250:14250' # Jaeger HTTP endpoint
      - '4317:4317' # Jaeger Collector
    networks:
      - be-template-network

  prometheus:
    image: prom/prometheus:latest
    container_name: be-template-prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./prometheus_data:/prometheus
      - ./src/common/opentelemetry/prometheus.yml:/etc/prometheus/prometheus.yml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0 # Use latest or specific version
    container_name: be-template-otel-collector
    restart: always
    command: [ '--config=/etc/otel-collector/otel-collector.yml' ]
    ports:
      - '1888:1888' # pprof extension
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '4318:4318' # OTLP HTTP receiver
      - '55679:55679' # zpages extension
    volumes:
      - ./src/common/opentelemetry/otel-collector.yml:/etc/otel-collector/otel-collector.yml # Mount your configuration file
    depends_on:
      - jaeger
    networks:
      - be-template-network

  grafana:
    image: grafana/grafana:latest
    container_name: be-template-grafana
    ports:
      - '3005:3000'
    env_file:
      - .env
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - be-template-network

volumes:
  mysql:


networks:
  be-template-network:
